# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-22 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstsite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='headerlink',
            name='content',
            field=models.TextField(blank=True, max_length=3000),
        ),
    ]
