# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-22 14:16
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('firstsite', '0002_headerlink_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headerlink',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
