# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-22 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstsite', '0003_auto_20180222_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='headerlink',
            name='content',
        ),
        migrations.AddField(
            model_name='headerlink',
            name='detailtext',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='headerlink',
            name='titletext',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
