# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-22 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstsite', '0005_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='headerlink',
            name='show',
            field=models.BigIntegerField(blank=True, default=1),
        ),
    ]
