# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-26 05:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstsite', '0005_auto_20180226_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='headerlink',
            name='content',
        ),
    ]
