# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-26 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstsite', '0007_headerlink_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='lantype',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('cn', 'Chinese'), ('ja', 'Japanese')], max_length=10),
        ),
    ]
