# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-26 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstsite', '0008_post_lantype'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='appcode',
            field=models.CharField(blank=True, choices=[('mainsite', '1'), ('mycareer', '2')], default='1', max_length=5),
        ),
        migrations.AlterField(
            model_name='post',
            name='lantype',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('cn', 'Chinese'), ('ja', 'Japanese')], default='en', max_length=10),
        ),
    ]
