# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-14 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstsite', '0011_headerlink_background_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='show',
            field=models.CharField(blank=True, choices=[('0', 'not show'), ('1', 'not show')], default='1', max_length=5),
        ),
    ]
