# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-29 02:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstsite', '0012_post_show'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='show',
            field=models.CharField(blank=True, choices=[('0', 'not show'), ('1', 'show')], default='1', max_length=5),
        ),
    ]
